export const metadata= {
  title: "Página de inicio",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div >
      <h1>hola mundo</h1>
    </div>
  );
}
